# Generated by Django 5.1.5 on 2025-02-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
